"""Version and build metadata — auto-generated by the build system.

Do not edit this file directly.
"""

__version__ = '0.1.0'

__build__ = 56

__build_date__ = '2026-05-31T17:50:25.753155+00:00'

__commit__ = 'fe57862'
