"""Version and build metadata — auto-generated by the build system.

Do not edit this file directly.
"""

__version__ = '0.1.0'

__build__ = 51

__build_date__ = '2026-05-31T14:16:35.017711+00:00'

__commit__ = 'e79863e'
