"""Bump the build number and regenerate src/harness/_version.py.

Called by ``make version-bump`` or ``make build``.
Usage: python3 scripts/version-bump.py [--reset]
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = PROJECT_ROOT / "src" / "harness" / "_version.py"
BUILD_FILE = PROJECT_ROOT / "BUILD_NUMBER"


def bump() -> int:
    """Read BUILD_NUMBER, increment, write _version.py.

    Returns the new build number.
    """
    # Read current build number
    current = 0
    if BUILD_FILE.exists():
        current = int(BUILD_FILE.read_text().strip() or "0")
    new_build = current + 1
    BUILD_FILE.write_text(f"{new_build}\n")

    # Read version from pyproject.toml
    try:
        import tomllib  # Python 3.11+
    except ImportError:
        import tomli as tomllib  # Python 3.9-3.10

    with open(PROJECT_ROOT / "pyproject.toml", "rb") as f:
        meta = tomllib.load(f)
    ver = meta["project"]["version"]

    # Write _version.py
    now = datetime.datetime.now(datetime.timezone.utc).isoformat()
    VERSION_FILE.write_text(
        f'"""Version and build metadata — auto-generated by the build system.\n\n'
        f'Do not edit this file directly.\n"""\n\n'
        f'__version__ = {ver!r}\n\n'
        f'__build__ = {new_build}\n\n'
        f'__build_date__ = {now!r}\n'
    )

    print(f"Bumped to v{ver}.{new_build:03d}")
    return new_build


def reset() -> None:
    """Reset BUILD_NUMBER to 0 and regenerate _version.py with build=0."""
    BUILD_FILE.write_text("0\n")
    VERSION_FILE.write_text(
        f'"""Version and build metadata — auto-generated by the build system.\n\n'
        f'Do not edit this file directly.\n"""\n\n'
        f'__version__ = "0.1.0"\n\n'
        f'__build__ = 0\n\n'
        f'__build_date__ = ""\n'
    )
    print("Reset to v0.1.0.000 (development mode)")


def main() -> None:
    parser = argparse.ArgumentParser(description="Bump dev-harness build number")
    parser.add_argument("--reset", action="store_true", help="Reset to build 0")
    args = parser.parse_args()

    if args.reset:
        reset()
    else:
        bump()


if __name__ == "__main__":
    main()
